# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: SMS text
      shell: bash
      run: |
        chmod +x ./setEnv.sh
        ./setEnv.sh ${{ secrets.MSISDN_RECEIVER }} ${{ secrets.MSISDN_SENDER }} ${{ secrets.TWILIO_ACCOUNT_SID }} ${{ secrets.TWILIO_AUTH_TOKEN }}
    - name: NPM ops
      shell: bash
      run: |
        yarn
        yarn start
      env:
        MSISDN_RECEIVER: ${{secrets.MSISDN_RECEIVER }}
        MSISDN_SENDER: ${{secrets.MSISDN_SENDER }}
        TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN }}
    - name: SMS text
      shell: bash
      run: chmod +x ./sendSms.sh && ./sendSms.sh
      env:
        CI: true
        API_KEY: ${{ secrets.API_KEY }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        #TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        #TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
        MSISDN_SENDER: ${{ secrets.MSISDN_SENDER }}
        MSISDN_RECEIVER: ${{ secrets.MSISDN_RECEIVER }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: sms
        path: sms.txt