# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM ops
      shell: bash
      run: |
        yarn
        yarn start
      env:
        CI: true
        MSISDN_RECEIVERS_DELIMITED_WITH_SEMICOLON: ${{ secrets.MSISDN_RECEIVERS_DELIMITED_WITH_SEMICOLON }}
        MSISDN_SENDER: ${{ secrets.MSISDN_SENDER }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: sms
        path: sms.txt